<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;
use App\AttributeDropdown;

class CreateAttributeDropdownsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('attribute_dropdowns', function (Blueprint $table) {
            $table->increments('id');
            $table->integer('attribute_id')->unsigned();
            $table->foreign('attribute_id')->references('id')->on('attributes')->onDelete('cascade');      
            $table->string('name');
            $table->timestamps();           
        });

        $attributes = array(
            // MOBILE PHONE - SUBCAT_ID 23
            array('name'=>'Samsung', 'attribute_id'=>'1'),
            array('name'=>'Apple', 'attribute_id'=>'1'),
            array('name'=>'HTC', 'attribute_id'=>'1'),            
            array('name'=>'LG', 'attribute_id'=>'1'),
            array('name'=>'Huawei', 'attribute_id'=>'1'),
            array('name'=>'Xiaomi', 'attribute_id'=>'1'),
            array('name'=>'Android', 'attribute_id'=>'2'),
            array('name'=>'Windows', 'attribute_id'=>'2'),
            array('name'=>'iOS', 'attribute_id'=>'2'),
            array('name'=>'1', 'attribute_id'=>'3'),
            array('name'=>'2', 'attribute_id'=>'3'),
            array('name'=>'3', 'attribute_id'=>'3'),
            array('name'=>'4', 'attribute_id'=>'3'),
            array('name'=>'6', 'attribute_id'=>'3'),
            array('name'=>'8', 'attribute_id'=>'3'),
            array('name'=>'Other', 'attribute_id'=>'3'),
            array('name'=>'64 MB', 'attribute_id'=>'5'),
            array('name'=>'128 MB', 'attribute_id'=>'5'),
            array('name'=>'256 MB', 'attribute_id'=>'5'),
            array('name'=>'512 MB', 'attribute_id'=>'5'),
            array('name'=>'768 MB', 'attribute_id'=>'5'),
            array('name'=>'1024 MB', 'attribute_id'=>'5'),
            array('name'=>'2 GB', 'attribute_id'=>'5'),
            array('name'=>'3 GB', 'attribute_id'=>'5'),
            array('name'=>'4 GB', 'attribute_id'=>'5'),
            array('name'=>'6 GB', 'attribute_id'=>'5'),
            array('name'=>'8 GB', 'attribute_id'=>'5'),
            array('name'=>'Other', 'attribute_id'=>'5'),
            array('name'=>'1.8', 'attribute_id'=>'6'),
            array('name'=>'2.0', 'attribute_id'=>'6'),
            array('name'=>'2.2', 'attribute_id'=>'6'),
            array('name'=>'2.4', 'attribute_id'=>'6'),
            array('name'=>'2.6', 'attribute_id'=>'6'),
            array('name'=>'2.8', 'attribute_id'=>'6'),
            array('name'=>'3.0', 'attribute_id'=>'6'),
            array('name'=>'3.2', 'attribute_id'=>'6'),
            array('name'=>'3.4', 'attribute_id'=>'6'),
            array('name'=>'3.5', 'attribute_id'=>'6'),
            array('name'=>'3.6', 'attribute_id'=>'6'),
            array('name'=>'3.7', 'attribute_id'=>'6'),
            array('name'=>'3.8', 'attribute_id'=>'6'),
            array('name'=>'3.9', 'attribute_id'=>'6'),
            array('name'=>'4.0', 'attribute_id'=>'6'),
            array('name'=>'4.2', 'attribute_id'=>'6'),
            array('name'=>'4.3', 'attribute_id'=>'6'),
            array('name'=>'4.5', 'attribute_id'=>'6'),
            array('name'=>'4.7', 'attribute_id'=>'6'),
            array('name'=>'4.8', 'attribute_id'=>'6'),
            array('name'=>'5.0', 'attribute_id'=>'6'),
            array('name'=>'5.1', 'attribute_id'=>'6'),
            array('name'=>'5.2', 'attribute_id'=>'6'),
            array('name'=>'5.5', 'attribute_id'=>'6'),
            array('name'=>'5.7', 'attribute_id'=>'6'),
            array('name'=>'5.8', 'attribute_id'=>'6'),
            array('name'=>'6.0', 'attribute_id'=>'6'),
            array('name'=>'6.2', 'attribute_id'=>'6'),
            array('name'=>'6.4', 'attribute_id'=>'6'),
            array('name'=>'7.0', 'attribute_id'=>'6'),
            array('name'=>'8.0', 'attribute_id'=>'6'),
            array('name'=>'9.0', 'attribute_id'=>'6'),
            array('name'=>'10', 'attribute_id'=>'6'),
            array('name'=>'< 10', 'attribute_id'=>'6'),
            array('name'=>'Other', 'attribute_id'=>'6'),
            array('name'=>'No', 'attribute_id'=>'7'),
            array('name'=>'Less than half a year', 'attribute_id'=>'7'),
            array('name'=>'half a year', 'attribute_id'=>'7'),
            array('name'=>'years', 'attribute_id'=>'7'),
            array('name'=>'2 year', 'attribute_id'=>'7'),
            array('name'=>'3 year', 'attribute_id'=>'7'),
            array('name'=>'mini SIM', 'attribute_id'=>'8'),
            array('name'=>'micro SIM', 'attribute_id'=>'8'),
            array('name'=>'nano SIM', 'attribute_id'=>'8'),
            array('name'=>'No', 'attribute_id'=>'9'),
            array('name'=>'> 1 MP', 'attribute_id'=>'9'),
            array('name'=>'1.3 MP', 'attribute_id'=>'9'),
            array('name'=>'2 MP', 'attribute_id'=>'9'),
            array('name'=>'3 MP', 'attribute_id'=>'9'),
            array('name'=>'5 MP', 'attribute_id'=>'9'),
            array('name'=>'8 MP', 'attribute_id'=>'9'),
            array('name'=>'12 MP', 'attribute_id'=>'9'),
            array('name'=>'13 MP', 'attribute_id'=>'9'),
            array('name'=>'14 MP', 'attribute_id'=>'9'),
            array('name'=>'16 MP', 'attribute_id'=>'9'),
            array('name'=>'20 MP', 'attribute_id'=>'9'),
            array('name'=>'< 20 MP', 'attribute_id'=>'9'),
            array('name'=>'Other', 'attribute_id'=>'9'),
            array('name'=>'> 1 MP', 'attribute_id'=>'10'),
            array('name'=>'1.3 MP', 'attribute_id'=>'10'),
            array('name'=>'2 MP', 'attribute_id'=>'10'),
            array('name'=>'3 MP', 'attribute_id'=>'10'),
            array('name'=>'5 MP', 'attribute_id'=>'10'),
            array('name'=>'8 MP', 'attribute_id'=>'10'),
            array('name'=>'12 MP', 'attribute_id'=>'10'),
            array('name'=>'13 MP', 'attribute_id'=>'10'),
            array('name'=>'14 MP', 'attribute_id'=>'10'),
            array('name'=>'16 MP', 'attribute_id'=>'10'),
            array('name'=>'20 MP', 'attribute_id'=>'10'),
            array('name'=>'< 20 MP', 'attribute_id'=>'10'),
            array('name'=>'Other', 'attribute_id'=>'10'),  
            array('name'=>'LED', 'attribute_id'=>'11'),
            array('name'=>'Dual-LED', 'attribute_id'=>'11'),
            array('name'=>'Xenon', 'attribute_id'=>'11'),
            array('name'=>'Other', 'attribute_id'=>'11'),
            array('name'=>'White', 'attribute_id'=>'12'),
            array('name'=>'Black', 'attribute_id'=>'12'),
            array('name'=>'Red', 'attribute_id'=>'12'),
            array('name'=>'Orange', 'attribute_id'=>'12'),
            array('name'=>'Blue', 'attribute_id'=>'12'),
            array('name'=>'Pink', 'attribute_id'=>'12'),
            array('name'=>'Brown', 'attribute_id'=>'12'),
            array('name'=>'Silver', 'attribute_id'=>'12'),
            array('name'=>'Gold', 'attribute_id'=>'12'),
            array('name'=>'Yellow', 'attribute_id'=>'12'),
            array('name'=>'Multiple color', 'attribute_id'=>'12'),
            array('name'=>'Other', 'attribute_id'=>'12'),
            array('name'=>'< 128 MB', 'attribute_id'=>'13'),
            array('name'=>'128 MB', 'attribute_id'=>'13'),
            array('name'=>'256 MB', 'attribute_id'=>'13'),
            array('name'=>'512 MB', 'attribute_id'=>'13'),
            array('name'=>'1 GB', 'attribute_id'=>'13'),
            array('name'=>'2 GB', 'attribute_id'=>'13'),
            array('name'=>'4 GB', 'attribute_id'=>'13'),
            array('name'=>'8 GB', 'attribute_id'=>'13'),
            array('name'=>'16 GB', 'attribute_id'=>'13'),
            array('name'=>'32 GB', 'attribute_id'=>'13'),
            array('name'=>'64 GB', 'attribute_id'=>'13'),
            array('name'=>'128 GB', 'attribute_id'=>'13'),
            array('name'=>'Other', 'attribute_id'=>'13'),
            array('name'=>'microSD', 'attribute_id'=>'14'),
            array('name'=>'miniSD', 'attribute_id'=>'14'),
            array('name'=>'SD', 'attribute_id'=>'14'),
            array('name'=>'RS-MMC', 'attribute_id'=>'14'),
            array('name'=>'Memory Stick Micro', 'attribute_id'=>'14'),
            array('name'=>'Memory Stick Duo', 'attribute_id'=>'14'),
            array('name'=>'Memory Stick Pro', 'attribute_id'=>'14'),
            array('name'=>'Other', 'attribute_id'=>'14'),
            array('name'=>'BH Telecom', 'attribute_id'=>'15'),
            array('name'=>'M-Tel', 'attribute_id'=>'15'),
            array('name'=>'Other', 'attribute_id'=>'15'),
            array('name'=>'256 MB', 'attribute_id'=>'16'),
            array('name'=>'512 MB', 'attribute_id'=>'16'),
            array('name'=>'1 GB', 'attribute_id'=>'16'),
            array('name'=>'2 GB', 'attribute_id'=>'16'),
            array('name'=>'4 GB', 'attribute_id'=>'16'),
            array('name'=>'8 GB', 'attribute_id'=>'16'),
            array('name'=>'16 GB', 'attribute_id'=>'16'),
            array('name'=>'32 GB', 'attribute_id'=>'16'),
            array('name'=>'64 GB', 'attribute_id'=>'16'),
            array('name'=>'128 GB', 'attribute_id'=>'16'),
            array('name'=>'256 GB', 'attribute_id'=>'16'),
            array('name'=>'> 256 GB', 'attribute_id'=>'16'),
            array('name'=>'With a contract', 'attribute_id'=>'17'),
            array('name'=>'No contract', 'attribute_id'=>'17'),

            //CAR SUBCAT_ID 1
            array('name'=>'BMW', 'attribute_id'=>'26'),
            array('name'=>'Audi', 'attribute_id'=>'26'),
            array('name'=>'Volkswagen', 'attribute_id'=>'26'),
            array('name'=>'Volvo', 'attribute_id'=>'26'),
            array('name'=>'Škoda', 'attribute_id'=>'26'),
            array('name'=>'Seat', 'attribute_id'=>'26'),
            array('name'=>'Other', 'attribute_id'=>'26'),
            array('name'=>'2019', 'attribute_id'=>'28'),
            array('name'=>'2018', 'attribute_id'=>'28'),
            array('name'=>'2017', 'attribute_id'=>'28'),
            array('name'=>'2016', 'attribute_id'=>'28'),
            array('name'=>'2015', 'attribute_id'=>'28'),
            array('name'=>'2014', 'attribute_id'=>'28'),
            array('name'=>'2013', 'attribute_id'=>'28'),
            array('name'=>'2012', 'attribute_id'=>'28'),
            array('name'=>'2011', 'attribute_id'=>'28'),
            array('name'=>'2010', 'attribute_id'=>'28'),
            array('name'=>'2009', 'attribute_id'=>'28'),
            array('name'=>'2008', 'attribute_id'=>'28'),
            array('name'=>'2007', 'attribute_id'=>'28'),
            array('name'=>'2006', 'attribute_id'=>'28'),
            array('name'=>'2005', 'attribute_id'=>'28'),
            array('name'=>'2004', 'attribute_id'=>'28'),
            array('name'=>'2003', 'attribute_id'=>'28'),
            array('name'=>'2002', 'attribute_id'=>'28'),
            array('name'=>'2001', 'attribute_id'=>'28'),
            array('name'=>'2000', 'attribute_id'=>'28'),
            array('name'=>'0.8', 'attribute_id'=>'30'),
            array('name'=>'0.9', 'attribute_id'=>'30'),
            array('name'=>'1.0', 'attribute_id'=>'30'),
            array('name'=>'1.1', 'attribute_id'=>'30'),
            array('name'=>'1.2', 'attribute_id'=>'30'),
            array('name'=>'1.3', 'attribute_id'=>'30'),
            array('name'=>'1.4', 'attribute_id'=>'30'),
            array('name'=>'1.5', 'attribute_id'=>'30'),
            array('name'=>'1.6', 'attribute_id'=>'30'),
            array('name'=>'1.7', 'attribute_id'=>'30'),
            array('name'=>'1.8', 'attribute_id'=>'30'),
            array('name'=>'1.9', 'attribute_id'=>'30'),
            array('name'=>'2.0', 'attribute_id'=>'30'),
            array('name'=>'2.1', 'attribute_id'=>'30'),
            array('name'=>'2.2', 'attribute_id'=>'30'),
            array('name'=>'2.3', 'attribute_id'=>'30'),
            array('name'=>'2.4', 'attribute_id'=>'30'),
            array('name'=>'2.5', 'attribute_id'=>'30'),
            array('name'=>'2.6', 'attribute_id'=>'30'),
            array('name'=>'2.7', 'attribute_id'=>'30'),
            array('name'=>'2.8', 'attribute_id'=>'30'),
            array('name'=>'2.9', 'attribute_id'=>'30'),
            array('name'=>'3.0', 'attribute_id'=>'30'),
            array('name'=>'3.1', 'attribute_id'=>'30'),
            array('name'=>'3.2', 'attribute_id'=>'30'),
            array('name'=>'3.3', 'attribute_id'=>'30'),
            array('name'=>'3.4', 'attribute_id'=>'30'),
            array('name'=>'3.5', 'attribute_id'=>'30'),
            array('name'=>'3.6', 'attribute_id'=>'30'),
            array('name'=>'3.7', 'attribute_id'=>'30'),
            array('name'=>'3.8', 'attribute_id'=>'30'),
            array('name'=>'3.9', 'attribute_id'=>'30'),
            array('name'=>'4.0', 'attribute_id'=>'30'),
            array('name'=>'4.1', 'attribute_id'=>'30'),
            array('name'=>'4.2', 'attribute_id'=>'30'),
            array('name'=>'4.3', 'attribute_id'=>'30'),
            array('name'=>'4.4', 'attribute_id'=>'30'),
            array('name'=>'4.5', 'attribute_id'=>'30'),
            array('name'=>'4.6', 'attribute_id'=>'30'),
            array('name'=>'4.7', 'attribute_id'=>'30'),
            array('name'=>'4.8', 'attribute_id'=>'30'),
            array('name'=>'4.9', 'attribute_id'=>'30'),
            array('name'=>'5.0', 'attribute_id'=>'30'),
            array('name'=>'5.1', 'attribute_id'=>'30'),
            array('name'=>'5.2', 'attribute_id'=>'30'),
            array('name'=>'5.3', 'attribute_id'=>'30'),
            array('name'=>'5.4', 'attribute_id'=>'30'),
            array('name'=>'5.5', 'attribute_id'=>'30'),
            array('name'=>'5.6', 'attribute_id'=>'30'),
            array('name'=>'5.7', 'attribute_id'=>'30'),
            array('name'=>'5.8', 'attribute_id'=>'30'),
            array('name'=>'5.9', 'attribute_id'=>'30'),
            array('name'=>'6.0', 'attribute_id'=>'30'),
            array('name'=>'6.1', 'attribute_id'=>'30'),
            array('name'=>'6.2', 'attribute_id'=>'30'),
            array('name'=>'6.3', 'attribute_id'=>'30'),
            array('name'=>'6.4', 'attribute_id'=>'30'),
            array('name'=>'6.5', 'attribute_id'=>'30'),
            array('name'=>'6.6', 'attribute_id'=>'30'),
            array('name'=>'6.7', 'attribute_id'=>'30'),
            array('name'=>'6.8', 'attribute_id'=>'30'),
            array('name'=>'6.9', 'attribute_id'=>'30'),
            array('name'=>'7.0', 'attribute_id'=>'30'),
            array('name'=>'7.1', 'attribute_id'=>'30'),
            array('name'=>'7.2', 'attribute_id'=>'30'),
            array('name'=>'7.3', 'attribute_id'=>'30'),
            array('name'=>'7.4', 'attribute_id'=>'30'),
            array('name'=>'7.5', 'attribute_id'=>'30'),
            array('name'=>'Benzine', 'attribute_id'=>'31'),
            array('name'=>'Diesel', 'attribute_id'=>'31'),
            array('name'=>'Gas', 'attribute_id'=>'31'),
            array('name'=>'Hybrid', 'attribute_id'=>'31'),
            array('name'=>'Electric', 'attribute_id'=>'31'),
            array('name'=>'2/3', 'attribute_id'=>'32'),
            array('name'=>'4/5', 'attribute_id'=>'32'),
            array('name'=>'Limousine', 'attribute_id'=>'36'),
            array('name'=>'Mini van', 'attribute_id'=>'36'),
            array('name'=>'Van', 'attribute_id'=>'36'),
            array('name'=>'Terrain', 'attribute_id'=>'36'),
            array('name'=>'Convertible', 'attribute_id'=>'36'),
            array('name'=>'Sport', 'attribute_id'=>'36'),
            array('name'=>'Off-road', 'attribute_id'=>'36'),
            array('name'=>'Caddy', 'attribute_id'=>'36'),
            array('name'=>'Pick-up', 'attribute_id'=>'36'),
            array('name'=>'Oldtimer', 'attribute_id'=>'36'),
            array('name'=>'Other', 'attribute_id'=>'36'),
            array('name'=>'Electric', 'attribute_id'=>'37'),
            array('name'=>'Front', 'attribute_id'=>'37'),
            array('name'=>'Last', 'attribute_id'=>'37'),
            array('name'=>'All foure', 'attribute_id'=>'37'),
            array('name'=>'Euro 0', 'attribute_id'=>'38'),
            array('name'=>'Euro 1', 'attribute_id'=>'38'),
            array('name'=>'Euro 2', 'attribute_id'=>'38'),
            array('name'=>'Euro 3', 'attribute_id'=>'38'),
            array('name'=>'Euro 4', 'attribute_id'=>'38'),
            array('name'=>'Euro 5', 'attribute_id'=>'38'),
            array('name'=>'Euro 6', 'attribute_id'=>'38'),
            array('name'=>'13', 'attribute_id'=>'39'),
            array('name'=>'14', 'attribute_id'=>'39'),
            array('name'=>'15', 'attribute_id'=>'39'),
            array('name'=>'16', 'attribute_id'=>'39'),
            array('name'=>'17', 'attribute_id'=>'39'),
            array('name'=>'18', 'attribute_id'=>'39'),
            array('name'=>'19', 'attribute_id'=>'39'),
            array('name'=>'20', 'attribute_id'=>'39'),
            array('name'=>'21', 'attribute_id'=>'39'),
            array('name'=>'22', 'attribute_id'=>'39'),
            array('name'=>'Other', 'attribute_id'=>'39'),
            array('name'=>'Automatic', 'attribute_id'=>'40'),
            array('name'=>'Semi-automatic', 'attribute_id'=>'40'),
            array('name'=>'Manual', 'attribute_id'=>'40'),
            array('name'=>'3 + R', 'attribute_id'=>'41'),
            array('name'=>'4 + R', 'attribute_id'=>'41'),
            array('name'=>'5 + R', 'attribute_id'=>'41'),
            array('name'=>'6 + R', 'attribute_id'=>'41'),
            array('name'=>'7 + R', 'attribute_id'=>'41'),
            array('name'=>'8 + R', 'attribute_id'=>'41'),
            array('name'=>'9 + R', 'attribute_id'=>'41'),
            array('name'=>'CVT', 'attribute_id'=>'41'),
            // DO COLOR SAM STIGO
        );
        foreach($attributes as $attribute){
            AttributeDropdown::create($attribute);
        }          
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('attribute_dropdowns');
    }
}
